### ISSUE TITLE
Clerk components are not rendering on Remix Run + Vite

### ISSUE THREAD

**Issue by rodolphoasb** [clerk/javascript#2661] opened 2024-01-24 14:54 UTC
### Preliminary Checks

- [X] I have reviewed the documentation: https://clerk.com/docs

- [X] I have searched for existing issues: https://github.com/clerk/javascript/issues

- [X] I have not already reached out to Clerk support via email or Discord (if you have, no need to open an issue here)

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Clerk. Please ask questions in our Discord community: https://clerk.com/discord.

### Reproduction / Replay Link

https://github.com/rodolphoasb/clerk-error

### Publishable key

pk_test_b2JsaWdpbmctZ3VsbC00Ny5jbGVyay5hY2NvdW50cy5kZXYk

### Description

I think the title says it all. I'm importing and using the component but they just are not rendering.

![image](https://github.com/clerk/javascript/assets/8127858/d616251a-bf33-47b4-b24e-0084bad98c2c)
<img width="384" alt="image" src="https://github.com/clerk/javascript/assets/8127858/97b8dfb4-f50b-460f-bde8-03c4b5618758">

### Environment

```Shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 165.69 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.15 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    bun: 1.0.3 - ~/.bun/bin/bun
    Watchman: 2023.07.24.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 16.4
  npmPackages:
    @clerk/remix: ^3.1.16 => 3.1.16 
    @flydotio/dockerfile: ^0.5.0 => 0.5.0 
    @playwright/test: ^1.41.0 => 1.41.0 
    @remix-run/css-bundle: 2.5.1 => 2.5.1 
    @remix-run/dev: 2.5.1 => 2.5.1 
    @remix-run/eslint-config: 2.5.1 => 2.5.1 
    @remix-run/express: 2.5.1 => 2.5.1 
    @remix-run/node: 2.5.1 => 2.5.1 
    @remix-run/react: 2.5.1 => 2.5.1 
    @remix-run/testing: 2.5.1 => 2.5.1 
    @testing-library/jest-dom: ^6.2.0 => 6.2.0 
    @testing-library/react: ^14.1.2 => 14.1.2 
    @testing-library/user-event: ^14.5.2 => 14.5.2 
    @types/eslint: ^8.56.2 => 8.56.2 
    @types/express: ^4.17.21 => 4.17.21 
    @types/morgan: ^1.9.9 => 1.9.9 
    @types/react: ^18.2.48 => 18.2.48 
    @types/react-dom: ^18.2.18 => 18.2.18 
    @vitejs/plugin-react: ^4.2.1 => 4.2.1 
    @vitest/coverage-v8: ^1.2.1 => 1.2.1 
    all-contributors-cli: ^6.26.1 => 6.26.1 
    autoprefixer: ^10.4.17 => 10.4.17 
    chalk: ^5.3.0 => 5.3.0 
    cross-env: ^7.0.3 => 7.0.3 
    dotenv: ^16.3.1 => 16.3.1 
    eslint: ^8.56.0 => 8.56.0 
    eslint-config-prettier: ^9.1.0 => 9.1.0 
    eslint-plugin-simple-import-sort: ^10.0.0 => 10.0.0 
    express: ^4.18.2 => 4.18.2 
    inngest: ^3.11.0 => 3.11.0 
    isbot: ^4.4.0 => 4.4.0 
    jsdom: ^23.2.0 => 23.2.0 
    morgan: ^1.10.0 => 1.10.0 
    npm-run-all: ^4.1.5 => 4.1.5 
    postcss: ^8.4.33 => 8.4.33 
    prettier: ^3.2.4 => 3.2.4 
    prettier-plugin-tailwindcss: ^0.5.11 => 0.5.11 
    react: 18.3.0-canary-b30030471-20240117 => 18.3.0-canary-b30030471-20240117 
    react-dom: 18.3.0-canary-b30030471-20240117 => 18.3.0-canary-b30030471-20240117 
    remix-development-tools: ^3.7.2 => 3.7.2 
    remix-flat-routes: ^0.6.4 => 0.6.4 
    remix-typedjson: ^0.4.1 => 0.4.1 
    rimraf: ^5.0.5 => 5.0.5 
    tailwindcss: ^3.4.1 => 3.4.1 
    typescript: 5.1.6 => 5.1.6 
    vite: ^5.0.11 => 5.0.11 
    vite-tsconfig-paths: ^4.3.1 => 4.3.1 
    vitest: ^1.2.1 => 1.2.1
```

**Comment by nsb** [comment] 2024-02-03 12:52
I'm facing the same issue.

**Comment by royanger** [comment] 2024-02-05 20:58
Hi @rodolphoasb. I tested your repo and when I just cloned it, added my own keys (as a secret key is also needed) and ran the app I could see components not rendering. I also noticed that `window.Clerk` returned null in the dev console, indicating Clerk hadn't loaded.

The app looked fine. I deleted node_modules and the lock file, then ran `pnpm up` to install and upgrade packages and then `pnpm dev` to run the app. This resulted in the components rendering and Clerk loading.

Can you test this and see if it works for you? Can you also just update all packages in this repo and see if that helps with using `npm`.

![Firefox_Developer_Edition](https://github.com/clerk/javascript/assets/24333362/1a1d6073-f420-41ef-a7fe-037873f81092)

**Comment by royanger** [comment] 2024-02-25 22:44
@nsb reported that changes to their application resolved this issue, and there is no bug. With no reply from the OP at the this time, I'm going to close this Issue.

**Closed by royanger** 2024-02-25 22:44 UTC
Labels: needs-triage

**Comment by Kfnig24** [comment] 2024-03-17 17:31
Hello, I have the same issue. By looking at the terminal, I see these errors if it may help.
![Capture d’écran 2024-03-17 à 18 31 05](https://github.com/clerk/javascript/assets/60477500/1bb850f1-a2df-432d-af6e-b8264ab68c81)

**Comment by dimkl** [comment] 2024-03-19 12:02
@Kfnig24 it seems like this is related to the `optimized-deps` plugin. Could you check if this resolves your issue: https://github.com/vitejs/vite/discussions/8749#discussioncomment-4187108

**Comment by Kfnig24** [comment] 2024-03-19 14:06
It still doesn't work. It seems to have a problem with react, have an idea why ?

**Comment by dimkl** [comment] 2024-03-19 14:08
@Kfnig24 Could you share a repo that reproduces the issue to investigate it?

**Comment by Kfnig24** [comment] 2024-03-19 14:28
Here a repo: https://github.com/Kfnig24/remix-vite-error.
I let the routes:
 - /auth/sign-in
 - /auth/sign-up
 - /dashboard

Sorry, I can't publish the rest of the code.

**Comment by clerk-cookie** [comment] 2025-09-18 00:01
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
