### ISSUE TITLE
The ignore option for @clerk/upgrade is ignored

### ISSUE THREAD

**Issue by tmcw** [clerk/javascript#3238] opened 2024-04-22 13:37 UTC
### Preliminary Checks

- [X] I have reviewed the documentation: https://clerk.com/docs

- [X] I have searched for existing issues: https://github.com/clerk/javascript/issues

- [X] I have not already reached out to Clerk support via email or Discord (if you have, no need to open an issue here)

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Clerk. Please ask questions in our Discord community: https://clerk.com/discord.

### Reproduction

https://this-is-in-a-script

### Publishable key

pk_this_is_not_relevant

### Description

**Steps to reproduce:**

1. Run `npx @clerk/upgrade`
2. Try ignoring a folder

**Expected behavior:**

It ignores the folder

**Actual behavior:**

It doesn't:

https://github.com/clerk/javascript/assets/32314/a297dbec-be60-4858-a09d-fc8ad839a071

### Environment

```Shell
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M2
    Memory: 339.13 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.volta/tools/image/node/20.9.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 10.1.0 - ~/.volta/tools/image/node/20.9.0/bin/npm
    pnpm: 9.0.3 - ~/Library/pnpm/pnpm
    bun: 1.0.28 - ~/.bun/bin/bun
    Watchman: 2024.04.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 124.0.6367.61
    Chrome Canary: 126.0.6433.0
    Safari: 17.4.1
  npmPackages:
    @clerk/backend: ^1.0.0 => 1.0.0
    @clerk/clerk-sdk-node: ^5.0.0 => 5.0.0
    @clerk/remix: ^4.0.0 => 4.0.0
```

**Comment by LekoArts** [comment] 2024-04-24 09:28
Thanks for the issue! I can reproduce it locally and will work on a fix 👍

**Comment by LekoArts** [comment] 2024-04-24 12:06
Ok, so I pushed https://github.com/clerk/javascript/pull/2474/commits/5546a3cb62cb6e55ae317d722c737237d1505119 - the gist of it is:

One needs to use `**/public/**` to correctly ignore the folder. I looked at the docs of the library we're using a bit but it wasn't immediately clear to me how to "fix" this (to allow `public/**`).

I tried https://github.com/mrmlnc/fast-glob#basenamematch but that didn't work 🤷 

My change isn't released yet, once that's done I'll close this

**Comment by LekoArts** [comment] 2024-04-26 08:27
The fix is published now 👍

**Closed by LekoArts** 2024-04-26 08:27 UTC
Labels: confirmed

**Comment by BRKalow** [comment] 2024-05-20 21:11
Hey @tmcw 👋  Can you try specifying `**/public/**` instead?

**Comment by tmcw** [comment] 2024-05-29 15:37
I can, but that doesn't capture my actual intention - I want Clerk to ignore the root-level directory `/public`, not any directory anywhere in the project named `public`.

**Comment by tmcw** [comment] 2024-06-10 18:13
![CleanShot 2024-06-10 at 14 13 15@2x](https://github.com/clerk/javascript/assets/32314/a2dafafe-49ab-419b-864c-75ca5bd28f8d)

The glob for what gets scanned seems bizarrely wide - why is clerk/upgrade parsing a CSV file?

**Comment by jescalan** [comment] 2024-06-10 18:55
If it's in your repo and it isn't ignored, we will scan it. Adding `*.csv` to ignores should iron this out.

Unfortunately we couldn't really get into the weeds around trying to specify every file extension that could or could not have valid html/css/js in it - I think that would cause more issues than having it scan anything that is not obviously a static asset and use ignores to choose what's ignored 😁

**Comment by clerk-cookie** [comment] 2025-06-11 00:01
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
