### ISSUE TITLE
404 (not-found.tsx) triggered when logging out

### ISSUE THREAD

**Issue by tpiros** [clerk/javascript#3864] opened 2024-08-01 01:01 UTC
### Preliminary Checks

- [X] I have reviewed the documentation: https://clerk.com/docs

- [X] I have searched for existing issues: https://github.com/clerk/javascript/issues

- [X] I have not already reached out to Clerk support via email or Discord (if you have, no need to open an issue here)

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Clerk. Please ask questions in our Discord community: https://clerk.com/discord.

### Reproduction

https://github.com/tpiros/clerk-sample.git

### Publishable key

pk_test_Y29oZXJlbnQtcG9ueS02OC5jbGVyay5hY2NvdW50cy5kZXYk

### Description

In a Next.js project, when on a protected path, after signing out, if `not-found.tsx` is added at the root level of the project, the 404 page shows up for a moment before the user gets redirected to the the path specified via `<ClerkProvider>`'s  `afterSignOutUrl` prop.

To test, throttle the network down to Fast 3G at least to see the 404 page show up. Steps to reproduce: Sign in, Navigate to /protected, Sign out.

### Environment

```Shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M2
    Memory: 81.64 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - /usr/local/bin/node
    npm: 10.5.1 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 127.0.6533.74
    Chrome Canary: 129.0.6629.0
    Safari: 17.5
  npmPackages:
    @clerk/nextjs: ^5.2.8 => 5.2.8 
    @types/node: ^20 => 20.14.13 
    @types/react: ^18 => 18.3.3 
    @types/react-dom: ^18 => 18.3.0 
    daisyui: ^4.12.10 => 4.12.10 
    eslint: ^8 => 8.57.0 
    eslint-config-next: 14.2.5 => 14.2.5 
    next: 14.2.5 => 14.2.5 
    postcss: ^8 => 8.4.40 
    react: ^18 => 18.3.1 
    react-dom: ^18 => 18.3.1 
    tailwindcss: ^3.4.1 => 3.4.7 
    typescript: ^5 => 5.5.4
```

**Comment by Sasha95** [comment] 2024-08-05 11:35
same issue

**Comment by MarLapuz** [comment] 2024-08-06 15:48
Extending the `middleware.ts` does the job for me.

```typescript
export default clerkMiddleware(
  (auth, request) => {
  if (!auth().userId && !isPublicRoute(request)) {
    return auth().redirectToSignIn();
  }
  // rest of the middleware
}
```

**Comment by npbee** [comment] 2024-08-07 18:49
I'm hitting something similar that I think is related to this same issue. From what I can tell, when the sign out occurs you get a `POST` to the route you're currently on _before_ the redirect happens, which I think is kicked off from this [server action](https://github.com/clerk/javascript/blob/ca631fdb29d5c3966e6268cfef2579e341493080/packages/nextjs/src/app-router/server-actions.ts#L9) in the `ClerkProvider`. Somehow this makes it [here](https://github.com/clerk/javascript/blob/ca631fdb29d5c3966e6268cfef2579e341493080/packages/nextjs/src/server/clerkMiddleware.ts#L240) which I think is Clerk trying to force a 404.

In our case this is presenting as a `500` instead of a `404` I think because we have a custom domain on our dev environment. We get a `Failed to proxy https://ourdomain.com/clerk_1723055237546 Error: connect ECONNREFUSED 127.0.0.1:443`. I can reproduce this on the sample repo provided using a reverse proxy like Caddy in front of it. I'm happy to file this part as a separate issue if that's helpful!

**Comment by MisterJimson** [comment] 2024-08-07 19:35
We are seeing this as well.

**Comment by MichaelFrieze** [comment] 2024-08-27 16:52
> Extending the `middleware.ts` does the job for me.
> 
> ```ts
> export default clerkMiddleware(
>   (auth, request) => {
>   if (!auth().userId && !isPublicRoute(request)) {
>     return auth().redirectToSignIn();
>   }
> 
>   // other config here...
> }
> ```

This worked for me. Thanks.

**Comment by LekoArts** [comment] 2024-08-29 06:41
This should be fixed by https://github.com/clerk/javascript/pull/4001 and was released in https://github.com/clerk/javascript/blob/refs/heads/main/packages/clerk-js/CHANGELOG.md#5170.

Please remove any workaround you might have added and give it a try, you should automatically get the new version (In the network graph the request for `clerk.browser.js` will be for 5.17.0).

**Closed** 2024-09-02 08:22 UTC
Labels: bug, redirects

**Comment by MisterJimson** [comment] 2024-10-17 16:54
I'm seeing this again with `clerk.browser.js` at `5.27.0`.

**Comment by victor9000** [comment] 2025-02-21 09:54
This error is still being discussed in discord:
https://discord.com/channels/856971667393609759/1332653566921281577/1332653566921281577

And I just spent days chasing this bug down, so it's still an issue on:
@clerk/elements@0.22.23
@clerk/nextjs@6.12.0

My work around:
```ts
import { clerkMiddleware, createRouteMatcher } from '@clerk/nextjs/server';
import { NextResponse } from 'next/server';

// public
const isPublicRoute = createRouteMatcher([
  '/',
  '/sign-in(.*)',
  '/sign-up(.*)',
  '/api/webhook(.*)',
]);

// check everything that is not public
export default clerkMiddleware(async (auth, req) => {
  if (!isPublicRoute(req)) {
    const { userId, sessionId, redirectToSignIn } = await auth();
    if (!userId || !sessionId) {
      redirectToSignIn();
    }
    auth.protect();
  }
});

// skip next.js internals and all static files, unless found in search params
export const config = {
  matcher: [
    '/((?!_next|[^?]*\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)',
  ],
};
```
