### ISSUE TITLE
Having a complex Astro config throws "Converting circular structure to JSON" when using Clerk components.

### ISSUE THREAD

**Issue by ernestoalejo** [clerk/javascript#4142] opened 2024-09-10 21:10 UTC
### Preliminary Checks

- [X] I have reviewed the documentation: https://clerk.com/docs

- [X] I have searched for existing issues: https://github.com/clerk/javascript/issues

- [X] I have not already reached out to Clerk support via email or Discord (if you have, no need to open an issue here)

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Clerk. Please ask questions in our Discord community: https://clerk.com/discord.

### Reproduction

https://stackblitz.com/edit/github-rdq1n6?file=astro.config.mjs

### Publishable key

pk_test_YW1hemVkLXR1cmtleS02Mi5jbGVyay5hY2NvdW50cy5kZXYk

### Description

**Steps to reproduce:**

1. Initialize a new Astro project with Vue.
2. Add Clerk with the official quickstart: https://clerk.com/docs/quickstarts/astro

If the vue plugin, or any other complex enough config, is added before the Clerk plugin runs and reads the config then a `Converting circular structure to JSON` throws when trying to use the components.

This occurs because the Astro config is not guaranteed to be JSON serializable here: https://github.com/clerk/javascript/blob/b97b2c1cae5cb1e569708a8745c13d203beb81d9/packages/astro/src/integration/vite-plugin-astro-config.ts#L33

This also means that the plugin sees an incomplete vision of the config object depending on when it runs so it's not useful anyway.

From the reproduction:

```typescript
export default defineConfig({
  adapter: node({ mode: 'standalone' }),
  output: 'server',

  // Works
  integrations: [clerk()],

  // Works:
  // integrations: [clerk(), vue()],

  // Doesn't work, circular structure:
  // integrations: [vue(), clerk()],
});
```

**Expected behavior:**

It works with any Astro config file.

**Actual behavior:**

![image](https://github.com/user-attachments/assets/9726ff00-a525-472c-bf23-288bd735e37e)

### Environment

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @astrojs/node: ^8.3.3 => 8.3.3 
    @astrojs/vue: ^4.5.0 => 4.5.0 
    @clerk/astro: ^1.2.6 => 1.2.6 
    astro: ^4.15.4 => 4.15.4 
    vue: ^3.4.38 => 3.5.3
```

**Comment by wobsoriano** [comment] 2024-09-13 16:43
Hi, thanks for reporting this and providing good reproduction. I can confirm this issue on my end as well when I put the `clerk` integration as the last item in the integrations array:

<img width="453" alt="Screenshot 2024-09-13 at 9 29 05 AM" src="https://github.com/user-attachments/assets/0beab6bc-d430-429f-895e-dbac1999a95f">

A PR is opened fixing this one <3

**Comment by wobsoriano** [comment] 2024-09-13 17:01
Apologies for the reopening/closing but the PR fix is merged and should be available in the next release

**Comment by bbagherian** [comment] 2024-09-13 17:59
Still having a bug with the current release. A fix was to reverting back to version 1.0.5.

**Comment by wobsoriano** [comment] 2024-09-13 18:01
@bbagherian the fix for this will be available in the next release (1.3.3)

**Comment by tmilewski** [comment] 2024-09-16 17:38
@bbagherian These changes were released a few hours ago! I'm going to close this issue out, but feel free to re-open if you're still having issues. Thanks!

**Closed by tmilewski** 2024-09-16 17:38 UTC
Labels: needs-triage

**Comment by clerk-cookie** [comment] 2025-09-18 00:02
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
